# Generated by Django 4.1.3 on 2022-11-29 02:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MyBus', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tarifa',
            name='linea_colectivo',
            field=models.CharField(default=0, max_length=40),
            preserve_default=False,
        ),
    ]
